import{a as q,S as P,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",B="23963114-6d0d5d874ae460d9125bacd21";async function m(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await q.get(M,{params:s})).data}let $=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=document.querySelector(".gallery"),s=r.map(({webformatURL:a,largeImageURL:e,tags:o,likes:i,views:b,comments:w,downloads:S})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${o}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><span><b>Likes</b></span><span>${i}</span></div>
            <div class="image-info-item"><span><b>Views</b></span><span>${b}</span></div>
            <div class="image-info-item"><span><b>Comments</b></span><span>${w}</span></div>
            <div class="image-info-item"><span><b>Downloads</b></span><span>${S}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",s),$.refresh()}function E(){document.querySelector(".gallery").innerHTML=""}const f=document.querySelector(".load-more"),h=document.querySelector(".loader-wrapper");function y(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}function R(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}const v=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",c=1;const u=15;let p=0;v.addEventListener("submit",x);O.addEventListener("click",H);async function x(r){if(r.preventDefault(),l=v.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search term!",position:"topRight"});return}c=1,E(),L(),y();try{const{hits:t,totalHits:s}=await m(l,c,u);if(d(),t.length===0){n.warning({message:"Sorry, no images found. Try another query!",position:"topRight"});return}p=s,g(t),Math.ceil(p/u)>1&&R()}catch{d(),n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}}async function H(){c+=1,y();try{const{hits:r}=await m(l,c,u);d(),g(r);const t=Math.ceil(p/u);c>=t&&(L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch{d(),n.error({message:"Error while loading more images.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
