import{a as P,S as q,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const E="https://pixabay.com/api/",M="23963114-6d0d5d874ae460d9125bacd21";function g(r,t=1,i=15){const s={key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i};return P.get(E,{params:s}).then(e=>e.data)}let R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function p(r,t){const i=r.map(({webformatURL:s,largeImageURL:e,tags:o,likes:a,views:b,comments:w,downloads:S})=>`
        <li class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${s}" alt="${o}" class="gallery-image" />
          </a>
          <div class="image-info">
            <div class="image-info-item"><b>Likes</b><span>${a}</span></div>
            <div class="image-info-item"><b>Views</b><span>${b}</span></div>
            <div class="image-info-item"><b>Comments</b><span>${w}</span></div>
            <div class="image-info-item"><b>Downloads</b><span>${S}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",i),R.refresh()}function B(r){r.innerHTML=""}const h=document.querySelector(".loader-wrapper");function y(){h.classList.remove("is-hidden")}function d(){h.classList.add("is-hidden")}const L=document.querySelector(".form"),m=document.querySelector(".gallery"),f=document.querySelector(".load-more");let l="",c=1;const u=15;L.addEventListener("submit",$);f.addEventListener("click",O);async function $(r){if(r.preventDefault(),l=L.elements["search-text"].value.trim(),!l){n.warning({message:"Please enter a search term!",position:"topRight"});return}c=1,B(m),v(),y();try{const t=await g(l,c,u);if(d(),t.hits.length===0){n.warning({message:"Sorry, no images found. Try another query!",position:"topRight"});return}p(t.hits,m),t.totalHits>u&&x()}catch{d(),n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}}async function O(){c+=1,y();try{const r=await g(l,c,u);d(),p(r.hits,m);const t=Math.ceil(r.totalHits/u);c>=t&&(v(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:i}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}catch{d(),n.error({message:"Error while loading more images.",position:"topRight"})}}function x(){f.classList.remove("is-hidden")}function v(){f.classList.add("is-hidden")}
//# sourceMappingURL=index.js.map
